FROM python:3.8.3

WORKDIR /usr/src/app

ENV PYTHONUNBUFFERED 1
ENV REDIS_SERVER redis

RUN pip install --upgrade pip

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT ["celery", "-A", "worker.services", "worker", "--loglevel=INFO"]
